Add build script
redhat-performance/etcd-wrapper pull request #1
Opened 2023-08-01 12:09 UTC by sousinha97

Add build script

2023-08-07 09:57 UTC, dvalinrh requested changes

2023-08-07 09:57 UTC, dvalinrh commented on etcd/etcd-build
> +  dnf install go
Needs to work for Ubuntu also, which uses apt.

2023-08-07 09:57 UTC, dvalinrh commented on etcd/etcd-build
> +  git checkout v3.5.0 # or the version you want to build
Make the version number a variable, will make changing it easier if it is in more then one place.

2023-08-07 09:57 UTC, dvalinrh commented on etcd/etcd-build
> +#!/bin/bash
Overall.  Needs error handling.  Exit 0 if success, exit 1 if we failed.

2023-08-07 09:57 UTC, dvalinrh commented on etcd/etcd-build
> +	yum install epel-release.noarch
Need to handle ubuntu also.  Also either use yum or dnf, one or the other.

2025-05-06 12:07 UTC, kdvalin commented
Closing as this is very stale at this point

2025-05-06 12:07 UTC, closed without merging